### ISSUE TITLE
Google search

### ISSUE THREAD

**Issue by afetchko** [yagopv/BgEngine#1]
I added a post and ran the search for words used in the post but got no results returned.

**Comment by yagopv** [comment]
That textbox depends on google results. Crawling and indexing are processes which can take some time ...

I recommend you to read about the process in 

 https://sites.google.com/site/webmasterhelpforum/en

You can find information in the crawling and indexing section.

Is very important for you using webmaster tools and add by hand the url´s of the posts to google index. All of this stuff is explained in the link. Read it!! because is your objective by deploying this blog.... Analytics and Webmasters tools are very important in the process and you should learn about them.

Add the url of the post once published (you can do this 500 times per month) and with regularity add to index main tags, categories and home page with all links included in them (you can do this 10 per month).

SEO is a continuous process that requires regular processes to maintain visibility and growth.

By doing analysis and getting reporting with google tools you can improve you visibility a lot ...

**Comment by afetchko** [comment]
Hey Man! Thanks for the link. Sounds good. I've actually been using google analytics for a long time in my own site but have not used the custom search before. It would make sense that you have to submit the page to have the results show.  I thought you mentioned that submission was done automatically by BeEngine when you add a post. Is it that this is not happening because the test site is not registered with Google? Andrew   > Date: Thu, 21 Jun 2012 07:51:59 -0700

**Comment by yagopv** [comment]
No, you have to submit the page to google index on your own or wait for the google spider to crawl your site, but google can´t ensure that the page will be retrieved and indexed (If you have a high ranked page this is different of course :)).

The manual mode for doing this is like in this link explains http://support.google.com/webmasters/bin/answer.py?hl=en&answer=1352276

Is there any API for doing this automatic?? I don´t know but i don´t think so.

**Comment by afetchko** [comment]
Ah...  OK. I thought you mentioned that in an earlier email but I must have thinking of something else.I sure don't know of any way to automate Google index updates. It would be nice if we could figure that out though. We'd be rich!
